import type { ColumnKey, ExchangeTab, LeafColumn } from '@/types/pages/iboard';

export const PRICE_BOARD_TABS: ExchangeTab[] = [
    {
        key: 'vn30',
        type: 'single',
        option: { value: 'VN30', label: 'VN30' },
    },
    {
        key: 'hose',
        type: 'single',
        option: { value: 'HOSE', label: 'HOSE' },
    },
    {
        key: 'hnx30',
        type: 'single',
        option: { value: 'HNX30', label: 'HNX30' },
    },
    {
        key: 'hnx',
        type: 'single',
        option: { value: 'HNX', label: 'HNX' },
    },
    {
        key: 'upcom',
        type: 'single',
        option: { value: 'UPCOM', label: 'UPCOM' },
    },
    {
        key: 'warrant',
        type: 'single',
        option: { value: 'WARRANT', label: 'Chứng quyền' },
    },
    {
        key: 'etf',
        type: 'single',
        option: { value: 'ETF', label: 'ETF' },
    },
    {
        key: 'bond',
        type: 'single',
        option: { value: 'BOND', label: 'Trái phiếu' },
    },
    {
        key: 'odd-lot-group',
        type: 'dropdown',
        defaultLabel: 'Lô lẻ',
        options: [
            { value: 'LO-LE-HOSE', label: 'Lô lẻ HOSE' },
            { value: 'LO-LE-HNX', label: 'Lô lẻ HNX' },
            { value: 'LO-LE-UPCOM', label: 'Lô lẻ UPCOM' },
        ],
    },
];

export const LEAF_COLUMNS: LeafColumn[] = [
    { key: 'symbol', label: 'Mã' },
    { key: 'reference', label: 'TC' },
    { key: 'ceiling', label: 'Trần' },
    { key: 'floor', label: 'Sàn' },
    { key: 'totalVol', label: 'Tổng KL' },
    { key: 'totalVal', label: 'Tổng GT' },
    { key: 'bid3', label: 'Giá 3' },
    { key: 'bid3Vol', label: 'KL 3' },
    { key: 'bid2', label: 'Giá 2' },
    { key: 'bid2Vol', label: 'KL 2' },
    { key: 'bid1', label: 'Giá 1' },
    { key: 'bid1Vol', label: 'KL 1' },
    { key: 'price', label: 'Giá' },
    { key: 'vol', label: 'KL' },
    { key: 'change', label: '+/-' },
    { key: 'changePercent', label: '%' },
    { key: 'offer1', label: 'Giá 1' },
    { key: 'offer1Vol', label: 'KL 1' },
    { key: 'offer2', label: 'Giá 2' },
    { key: 'offer2Vol', label: 'KL 2' },
    { key: 'offer3', label: 'Giá 3' },
    { key: 'offer3Vol', label: 'KL 3' },
    { key: 'high', label: 'Cao' },
    { key: 'medium', label: 'TB' },
    { key: 'low', label: 'Thấp' },
    { key: 'foreignBought', label: 'Mua' },
    { key: 'foreignSold', label: 'Bán' },
    { key: 'foreignRemain', label: 'Dư' },
];

export const IBOARD_COLUMN_WIDTH_PX: Record<ColumnKey, number> = {
    symbol: 83,
    reference: 55,
    ceiling: 55,
    floor: 55,
    totalVol: 113,
    totalVal: 113,
    bid3: 55,
    bid3Vol: 73,
    bid2: 55,
    bid2Vol: 73,
    bid1: 55,
    bid1Vol: 73,
    price: 55,
    vol: 63,
    change: 63,
    changePercent: 63,
    offer1: 55,
    offer1Vol: 73,
    offer2: 55,
    offer2Vol: 73,
    offer3: 55,
    offer3Vol: 73,
    high: 55,
    medium: 55,
    low: 55,
    foreignBought: 73,
    foreignSold: 73,
    foreignRemain: 93,
};

export const IBOARD_TERTIARY_BG_COLUMN_KEYS = new Set<ColumnKey>([
    'reference',
    'ceiling',
    'floor',
    'totalVol',
    'totalVal',
    'price',
    'vol',
    'change',
    'changePercent',
    'high',
    'medium',
    'low',
]);

export const IBOARD_BID_ASK_PRICE_KEYS = new Set<ColumnKey>([
    'bid1',
    'bid2',
    'bid3',
    'offer1',
    'offer2',
    'offer3',
]);

export const ODD_LOT_EXCHANGES = new Set(['LO-LE-HOSE', 'LO-LE-HNX', 'LO-LE-UPCOM']);
export const INDEX_EXCHANGES = new Set(['VN30', 'HNX30']);
export const TYPE_EXCHANGES = new Set(['WARRANT', 'ETF', 'BOND']);

export const IBOARD = {
    page_title: 'Bảng giá',
    nav_label: 'Điều hướng bảng giá',
    stock_price_table: 'Bảng giá cổ phiếu',
    price_cell_trade_tooltip: 'Click để giao dịch',
    group_bid: 'Bên mua',
    group_match: 'Khớp lệnh',
    group_ask: 'Bên bán',
    group_price: 'Giá',
    group_foreign: 'ĐTNN',
    leaf_symbol: 'Mã',
    leaf_reference: 'TC',
    leaf_ceiling: 'Trần',
    leaf_floor: 'Sàn',
    leaf_totalVol: 'Tổng KL',
    leaf_totalVal: 'Tổng GT',
    leaf_bid3: 'Giá 3',
    leaf_bid3Vol: 'KL 3',
    leaf_bid2: 'Giá 2',
    leaf_bid2Vol: 'KL 2',
    leaf_bid1: 'Giá 1',
    leaf_bid1Vol: 'KL 1',
    leaf_price: 'Giá',
    leaf_vol: 'KL',
    leaf_change: '+/-',
    leaf_changePercent: '%',
    leaf_offer1: 'Giá 1',
    leaf_offer1Vol: 'KL 1',
    leaf_offer2: 'Giá 2',
    leaf_offer2Vol: 'KL 2',
    leaf_offer3: 'Giá 3',
    leaf_offer3Vol: 'KL 3',
    leaf_high: 'Cao',
    leaf_medium: 'TB',
    leaf_low: 'Thấp',
    leaf_foreignBought: 'Mua',
    leaf_foreignSold: 'Bán',
    leaf_foreignRemain: 'Dư',
    exchange_board_filter_nav: 'Lọc theo nhóm bảng giá',
    exchange_group_tablist: 'Nhóm sàn giao dịch',
    exchange_options_list_for: 'Danh sách {name}',
    index: {
        vol_label: 'KLGD:',
        val_label: 'GTGD:',
        val_unit: 'Tỷ',
        shares_unit: 'CP',
    },
};
